dashpay/electrum-dash

lib/util.py

updated explorer URL to dash.org

---

gui/qt/main_window.py
gui/qt/masternode_budget_widgets.py
gui/qt/masternode_dialog.py
gui/qt/masternode_widgets.py
lib/commands.py
lib/masternode.py
lib/masternode_budget.py
lib/masternode_manager.py
lib/network_proxy.py
lib/transaction.py

When the last PR (https://github.com/dashpay/electrum-dash/pull/22) was merged, whoever merged it missed the last 11 commits. These are those commits.

Add masternode functionality that wasn't merged

---

lib/masternode_manager.py

Fixes the exception raised in #27

MasternodeManager: Account for different proposals formats from server

---

lib/masternode.py
lib/tests/test_masternode.py

Accounts for https://github.com/dashpay/dash/pull/836

Change serialization for signatures depending on protocol version

---

RELEASE-NOTES
setup-release.py

This causes unnecessary merge conflicts with upsteam, readded for convenience
- readding setup-release.py
- restore original RELEASE-NOTES

revert unnecessary Dashification

---

.travis.yml
README.rst

I have reenabled the Travis-CI build for better test coverage.

fix Travis logo and build

---

lib/bitcoin.py

As per https://github.com/dashpay/dash/commit/c5004ce308e44cbe16b6253de714419e6962731b

Change testnet addr version to match updated dashd

---

lib/tests/test_bitcoin.py
plugins/__init__.py

This will facilitate the merge of Electrum 2.4.3 from upstream

reorder imports/tests/plugins

---

gui/qt/main_window.py

Electrum ---> Electrum-DASH

---

lib/network.py

It's appear that I changed my server name from drk to dash but still have drk available point to same ip address. I think it's time to request for change my server name to dash :)

Change server name

---

requirements.txt
setup.py

update to python-trezor-0.6.13

---

gui/qt/masternode_dialog.py
lib/masternode_budget.py
lib/masternode_manager.py

Use the new APIs for Transaction and WaitingDialog.

Use Electrum 2.6.4 in masternode-related modules

---

gui/qt/masternode_dialog.py

Fix formatting and printing of error traceback.

MasternodeDialog: Fix formatting/printing of traceback

---

gui/qt/masternode_dialog.py

Log messages are now preceded with `[MasternodeDialog]` and are displayed at more points throughout the masternode activation process.

Add more verbosity to masternode operations log

---

gui/qt/main_window.py
gui/qt/masternode_dialog.py
lib/network.py

As per @thelazier proposal subscriptions are disabled. The "Budget Proposals" tab is hidden, as well as the "Vote" tab in the Masternode Manager.

Disable proposals subscription

---

gui/qt/masternode_dialog.py
gui/qt/masternode_widgets.py
lib/commands.py
lib/masternode_manager.py
lib/wallet.py

Delegate private keys are no longer encrypted

Show masternode delegate privkey in Masternode Manager

---

plugins/trezor/plugin.py
plugins/trezor/trezor.py
requirements.txt
setup.py

Cherry-picking some commits from upstream to support python-trezor-0.7.0 to get rid of Windows USB issues.

Update to python-trezor-0.7.0

---

lib/masternode.py

Message format uses different endianess - fixed

fix serialization

---

lib/tests/test_masternode.py

Fix the test to reflect the fixed serialization

Fix masternode serialization test

---

plugins/trezor/plugin.py
plugins/trezor/trezor.py
requirements.txt
setup.py

Reverts dashpay/electrum-dash#70
Seems like the USB detection does not work properly

Revert "Update to python-trezor-0.7.0"

---

plugins/ledger/ledger.py

- This is based on pooler/electrum-ltc@f5433e0

Dash: properly set Ledger address versions

---

lib/network.py

Disconnect servers that report invalid versions or versions that are too low. This will make the transition to servers that support masternode operations easier.

Disconnect servers with invalid versions

---

plugins/trezor/plugin.py
plugins/trezor/trezor.py

Attempt to use TREZOR Bridge before the usual HID transport. For #21

Add support for TREZOR Bridge

---

icons/bg.png

This icons/bg.png is from @snogcel 's uploaded file in slack.

Add missing icons/bg.png

---

contrib/build-wine/deterministic.spec
contrib/build-wine/electrum-dash.nsi

Release scripts are in https://github.com/akhavr/electrum-dash-release

Update spec and nsi to match updated release scripts
